-d F:\FPGA\TangNano-9K-example-main\lcd_led\impl\gwsynthesis\Tang_nano_9K_LCD.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst F:\FPGA\TangNano-9K-example-main\lcd_led\src\Tang_nano_9K_LCD.cst
-cfg F:\FPGA\TangNano-9K-example-main\lcd_led\impl\pnr\device.cfg
-sdc F:\FPGA\TangNano-9K-example-main\lcd_led\src\Tang_nano_9K_LCD.sdc
-bit
-tr
-ph
-timing
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
